# Generated by Django 5.2.9 on 2026-01-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('track', models.CharField(choices=[('office', 'Office Track'), ('field', 'Field Track')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('essentials', 'Essentials'), ('fsl_app', 'FSL App'), ('customer_journey', 'Customer Journey')], db_index=True, max_length=50)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('embed_url', models.URLField(max_length=2000)),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('course', 'order'), name='unique_video_order_per_course')],
            },
        ),
    ]
