# Generated by Django 5.2.9 on 2026-01-13 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursestats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideoOpened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_opened_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_events', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_videos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_by', to='courses.coursevideo')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseStats',
        ),
        migrations.AddIndex(
            model_name='coursevideoopened',
            index=models.Index(fields=['user', 'course'], name='courses_cou_user_id_9924a4_idx'),
        ),
        migrations.AddIndex(
            model_name='coursevideoopened',
            index=models.Index(fields=['course', 'video'], name='courses_cou_course__029332_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursevideoopened',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='unique_open_per_user_video'),
        ),
    ]
