# Generated by Django 5.2.9 on 2026-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursequiz_quizquestion_quizchoice_quizsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('applications', 'Applications'), ('customer_journey', 'Customer Journey'), ('trades', 'Trades')], db_index=True, max_length=50),
        ),
    ]
