# Generated by Django 5.2.9 on 2026-01-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('applications', 'Applications'), ('customers', 'Customers'), ('damp_and_mould', 'Damp and Mould'), ('drains_and_blockage', 'Drains and Blockage'), ('electricians', 'Electricians'), ('fire_safety', 'Fire Safety'), ('heating_and_hot_water', 'Heating and Hot Water'), ('leak_detection', 'Leak Detection'), ('plumbing_and_cold_water', 'Plumbing and Cold Water'), ('roofing', 'Roofing'), ('air_conditioning_and_refrigeration', 'Air Conditioning and Refrigeration'), ('carpentry', 'Carpentry'), ('doors_windows_and_locks', 'Doors, Windowns and Locks'), ('fencing_decking_and_cladding', 'Fencing, Decking and Cladding'), ('flooring', 'Flooring'), ('gardening', 'Gardening'), ('handyman_and_odd_jobs', 'Handyman and Odd Jobs'), ('painting_and_decorating', 'Painting and Decorating'), ('paths_and_patios', 'Paths and Patios'), ('pest_control', 'Pest Control'), ('plastering_and_tiling', 'Plastering and Tiling'), ('refurbishment', 'Refurbishment'), ('rubbish_removal', 'Rubbish Removal'), ('sanitising_and_hygiene', 'Sanitising and Hygiene'), ('ventilation', 'Ventilation'), ('walls_and_ceilings', 'walls and Ceilings')], db_index=True, default='essentials', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('office', 'Office'), ('field', 'Field Engineers'), ('trades', 'Trades')], db_index=True, max_length=50),
        ),
    ]
