# Generated by Django 5.2.9 on 2026-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_subcategory_alter_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_times',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('applications', 'Applications'), ('customer_journey', 'Customer Journey'), ('trades', 'Trades')], db_index=True, max_length=50),
        ),
    ]
