# Generated by Django 5.2.9 on 2026-01-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_subcategory_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='attempted_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
