# Generated by Django 5.2.9 on 2026-01-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courseprogress_attempted_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='guide_title',
            field=models.CharField(blank=True, default='Open guide', max_length=255),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='guide_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
