# Generated by Django 5.2.9 on 2026-01-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursevideo_content_type_alter_course_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('applications', 'Applications'), ('customers', 'Customers'), ('building_fabric', 'Building Fabric'), ('drainage_and_plumbing', 'Drainage and Plumbing'), ('gas_and_electrical', 'Gas and Electrical'), ('fire_safety', 'Fire Safety'), ('environmental_services', 'Environmental Services'), ('aspect_principles', 'Aspect Principles')], db_index=True, max_length=50),
        ),
    ]
