# Generated by Django 5.2.9 on 2026-02-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_storage_folder_name_coursevideo_sp_drive_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumb_sp_drive_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='course',
            name='thumb_sp_item_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='course',
            name='thumb_sp_mime',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='thumb_sp_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='course',
            name='thumb_sp_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='thumb_sp_web_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
