# Generated by Django 5.2.9 on 2026-02-11 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_thumb_sp_drive_id_course_thumb_sp_item_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='quizanswer',
            name='unique_answer_per_question_per_submission',
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_answer_per_submission_question'),
        ),
        migrations.AddField(
            model_name='coursevideonote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_video_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursevideonote',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.coursevideo'),
        ),
        migrations.AddIndex(
            model_name='coursevideonote',
            index=models.Index(fields=['user', 'video'], name='courses_cou_user_id_a59b68_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursevideonote',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='unique_note_per_user_video'),
        ),
    ]
