# Generated by Django 5.2.9 on 2026-01-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_monthlyactiveusers_usermonthlylogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_create_courses',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
