# Generated by Django 5.2.9 on 2026-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='uniq_user_email_ci',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_display',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
